### ISSUE TITLE
A Tiny Issue

### ISSUE THREAD

**Issue by Kaijudo11** [emymin/EmyChess#8] opened 2023-03-30 18:17 UTC
Hello again. I noticed a little issue with your Chess Clock... everything works great! but.... you have the Chess clock set wrong. I looked up the official time rules to be sure of this. When a Chess match starts Black side starts the clock for White... your board is set to where White starts the clock for black, that's not the correct way to start a match.

Is there a way I can correct the clock in the scene? I tried on my own but couldn't seem to tweak the clock setup.

**Comment by emymin** [comment] 2023-03-31 18:43
Hello! I didn't know about this, thanks for bringing this to my attention! It should be a simple enough fix so I will be doing it as soon as I can!

**Comment by Kaijudo11** [comment] 2023-04-01 03:46
Thank you :)

**Comment by emymin** [comment] 2023-04-06 17:51
Sorry for taking a while to respond, I have been very busy! The issue is fixed on commit c249859 . The change is very small so I will not make a separate release for it yet, so I will keep the issue up until it is part of a release! To fix the issue, simply add `timer._StartCountDown(true);` right after line 287 in ChessManager.cs

**Comment by Kaijudo11** [comment] 2023-04-06 18:12
No worries.... I knew it would take some time. Thank you so much for addressing the issue. Me and my friends can't thank you enough. Cheers! :)

**Comment by Kaijudo11** [comment] 2023-04-06 20:38
I just added the line of code; it works excellently, thank you again 

Quick follow up question: I notice the line of code works for the automated version of the clock. Is there anyway to do the same for the manual version of the clock as well?

**Closed as completed** 2023-10-15 08:54 UTC
